### ISSUE TITLE
Unable to make chapter 17 listings due to stdc++fs library not found

### ISSUE THREAD

**Issue by MatthewVasseur** [JLospinoso/ccc#217]
I had trouble compiling the chapter 17 listings due to the error `ld: library not found for -lstdc++fs`

```
% make filesystem           
Consolidate compiler generated dependencies of target filesystem
[100%] Linking CXX executable filesystem
ld: library not found for -lstdc++fs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [chapter_17/filesystem] Error 1
make[2]: *** [chapter_17/CMakeFiles/filesystem.dir/all] Error 2
make[1]: *** [chapter_17/CMakeFiles/filesystem.dir/rule] Error 2
make: *** [filesystem] Error 2

% c++ -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I am running macOS Monterey 12.6.1. I believe this started happening after an update (to Xcode perhaps?).

**Comment by MatthewVasseur** [comment]
I (believe) this problem is solved by editing the `chapter_17/CMakeLists.txt` to use `stdc++` or `c++` instead of `stdc++fs`

e.g. 
```
target_link_libraries(filesystem PRIVATE stdc++fs ${Boost_SYSTEM_LIBRARY}) # error
target_link_libraries(filesystem PRIVATE c++ ${Boost_SYSTEM_LIBRARY}) # working
```

n.b. I am not entirely sure *why*

**Comment by dascandy** [comment]
This is reality catching up to a printed material. When the book was first written the C++ libraries didn't officially support <filesystem> yet, so they would require a secondary library called "stdc++fs". This was a libstdc++ specific library that did import the C++17 features that weren't in the official library yet.

Since a few years now though, both GCC's libstdc++ and Clang's libc++ include <filesystem> in their base library, and I think the (now empty) stdc++fs library got dropped.

In effect, you can drop the linking to that library without any problem; it patched a problem in compiler support that's no longer relevant. You don't need to mention `stdc++` or `c++` though, using `clang++` does that (and some other C++ specific things) for you.
