### ISSUE TITLE
Page 127, SimpleString constructor of SimpleStringOwner

### ISSUE THREAD

**Issue by sencai** [JLospinoso/ccc#48]
SimpleStringOwner(**SimpleString&&** x) : string{ std::move(x) } { }
should be
SimpleStringOwner(**SimpleString&** x) : string{ std::move(x) } { }

**Comment by JLospinoso** [comment]
Hi @sencai, thanks for reaching out! The reason it's `SimpleString&&` is so the method works with an rvalue. If we used an lvalue reference, it could be dangerous -- the caller's object would be in a moved-from state without appropriate warning.

**Comment by sencai** [comment]
> Hi @sencai, thanks for reaching out! The reason it's `SimpleString&&` is so the method works with an rvalue. If we used an lvalue reference, it could be dangerous -- the caller's object would be in a moved-from state without appropriate warning.

So you std::move an rvalue? Sry I'm not so familiar with std::move() but from what I've learned so far std::move() a lvalue to a rvalue.

**Comment by JLospinoso** [comment]
It's a bit confusing, but the text attempts to explain: 

"The x is an lvalue, so you must std::move x into the move constructor
of string u. You might find std::move odd, because x is an rvalue reference.
Recall that lvalue/rvalue and lvalue reference/rvalue reference are distinct
descriptors."

Even thought x is an rvalue reference, it's an lvalue, since it has a name. Does that make sense? In other words, from the caller's perspective, they provide an rvalue. From our perspective, this rvalue is bound to the rvalue reference x, which is itself an lvalue.

**Comment by sencai** [comment]
I've got what you mean. Thanks for clarification!

**Comment by shivamparke** [comment]
Hi. The SimpleStringOwner move constructor is:
`SimpleStringOwner(SimpleString&& x) : string{ std::move(x) } { }` 

When you pass a SimpleString to the SimpleStringOwner move constructor, you would pass it like:
`SimpleStringOwner b{std::move(a)};`

Thus, inside this move constructor, x is _already_ an rvalue reference. So what's the need for this statement:
`string{ std::move(x) }`
Could we not simply write
`string{ x }`
?
