### ISSUE TITLE
Page 261: Non-existant variable "l" (letter L) is used in code example. Should be "len" instead.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#88]
**This error is present in both the larger example box** (below "Listing 9-17 illustrates how to assign a generic lambda into a variable and then use the lambda in two different template instantiations.") **and also in the smaller example box** (just below "Without a generic lambda, you’d have to declare the parameter types explicitly, like the following:").

PS: The font you're using makes it very hard to distinguish between the number 1 and the letter L in lowercase. For future reference, a font that doesn't suffer from this problem is Deja Vu Sans Mono (see https://en.wikipedia.org/wiki/DejaVu_fonts#Sans_Mono).

This may have contributed to people not spotting the error until now. It looks too much like a valid number.

**Comment by JLospinoso** [comment]
Thanks, @wraithglade!

**Comment by nicebub** [comment]
On your website that explains this in the Errata, and what @WraithGlade did not specify is that this is on page 261 and on the top of page 262 where the "smaller" example can be found. 

Also What you explain on your website only discusses listing 9-17 and the use of 'l' instead of 'len' in the use of the transform functions but you didn't explain that the same error was made inside the 'for loop' at the bottom of the listing as well.

The code example for 9-17 in the chapter9 folder has not been changed on your GitHub yet to reflect your awareness and fix of the error.
  Thank you again for a great book.
